package com.group8.userlogin.controller;

import com.group8.userlogin.service.CustomerService;
import com.group8.userlogin.model.Customer;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import java.util.Random;

@ControllerAdvice
@Controller
public class CustomerController {

    //CRUD
    @Autowired
    private CustomerService customerService;


    @RequestMapping("/home")
    public String getAllCustomer(Model model) {
        model.addAttribute("getAllCustomer", customerService.getAllCustomerList());
        return "home";
    }


    @RequestMapping("/saveform")
    public String saveform(Model model) {
        Customer customer = new Customer();
        model.addAttribute("saveCustomer", customer);
        return "newCustomer";
    }

    @PostMapping("/save")
    public String save(@ModelAttribute("customer") Customer customer) {
        customerService.saveCustomer(customer);
        return "redirect:/home";
    }

    @RequestMapping("/delete/{id}")
    public String deleteCustomer(@PathVariable long id) {
        return customerService.deleteCustomer(id);
    }

    @PutMapping("/update")
    public Customer updateCustomer(@RequestBody Customer customer) {
        return customerService.updateCustomer(customer);
    }


    /*private static Logger logger = Logger.getLogger();

    @ExceptionHandler(Throwable.class)
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public String exception(final Throwable throwable, final Model model) {
        logger.error("Exception during execution of SpringSecurity application", throwable);
        String errorMessage = (throwable != null ? throwable.getMessage() : "Unknown error");
        model.addAttribute("errorMessage", errorMessage);
        return "error";*/



 /*Some type of 404 error */
/*    public class MyErrorController implements ErrorController {

        @RequestMapping("/error")
        public String handleError() {
        return "error";
        }

    } */

    /*Math random for thank you page - ticket number autogenerated something*/
    @GetMapping("/thankyou")
    public ModelAndView getMyPage() {
        return new ModelAndView("thankyou", "randomSkaicius", randomSkaicius());
    }

    public int randomSkaicius() {
        Random rand = new Random();
        int skaicius = (int) (Math.random() * 50 + 1);
        return skaicius;
    }


}



